### ISSUE TITLE
Log posthog events

### ISSUE THREAD

**Issue by jeznag** [Focus-Bear/late-no-more#22]
Events:
1. start-late-no-more-binary
2. stop-late-no-more-binary
3. apply-settings (when apply is clicked)
4. open-advanced-settings (when advanced settings is clicked)
5. modify-excluded-calendar-list (when excluded calendars are changed)

Project API key phc_vb06v8qtjM1nomW5U4CLXQMs83ym4kVh6Ki4H6Diqrx

**Comment by jeznag** [comment]
Did you use the correct project? I can't see any events yet in the late no more project

**Comment by manishjain999** [comment]
We used the above API key you shared..

`Project API key phc_vb06v8qtjM1nomW5U4CLXQMs83ym4kVh6Ki4H6Diqrx`
